### ISSUE TITLE
AttributeError: module 'easyesn.backend' has no attribute 'ptp'

### ISSUE THREAD

**Issue by tetsuyasu** [kalekiu/easyesn#6]
Thank you for publishing very useful library.
This works well on CPU.
But, I got an error when using on GPU (cupy).

AttributeError: module 'easyesn.backend' has no attribute 'ptp'

I think that numpy has ptp but cupy does not have it.

**Comment by denisj44** [comment]
I provided a merge request to fix it.
Cheers

**Comment by zimmerrol** [comment]
Fixed by #13.

**Comment by tetsuyasu** [comment]
Thank you, "AttributeError: module 'easyesn.backend' has no attribute 'ptp'" is solved.

But, I run the PredictionExample, the following error occurred.
I use cupy-cuda101==7.6.0.


Using Numpy backend.
100% (616 of 616) |#################################################################################| Elapsed Time: 0:00:00 Time:  0:00:00
100% (600 of 600) |#################################################################################| Elapsed Time: 0:00:00 Time:  0:00:00
(OK)


Using CuPy backend
100% (631 of 631) |#################################################################################| Elapsed Time: 0:00:00 Time:  0:00:00
100% (600 of 600) |#################################################################################| Elapsed Time: 0:00:00 Time:  0:00:00
Traceback (most recent call last):
  File "PredictionExample.py", line 42, in <module>
    generation = esn.generate(n=len(inputDataValidation), inputData=None, initialOutputData=inputDataTraining[-1])
  File "../src/easyesn/easyesn/PredictionESN.py", line 238, in generate
    _, Y = self.propagate(inputData, None, verbose=verbose, steps=n, previousOutputData=initialOutputData)
  File "../src/easyesn/easyesn/BaseESN.py", line 135, in propagate
    Y[t-transientTime, :] = previousOutputData
  File "cupy/core/core.pyx", line 1248, in cupy.core.core.ndarray.__setitem__
  File "cupy/core/_routines_indexing.pyx", line 49, in cupy.core._routines_indexing._ndarray_setitem
  File "cupy/core/_routines_indexing.pyx", line 811, in cupy.core._routines_indexing._scatter_op
  File "cupy/core/_kernel.pyx", line 930, in cupy.core._kernel.ufunc.__call__
  File "cupy/core/_kernel.pyx", line 404, in cupy.core._kernel._get_out_args
ValueError: Out shape is mismatched
(ERROR)

[PredictionExample.zip](https://github.com/kalekiu/easyesn/files/4969622/PredictionExample.zip)
